### ISSUE TITLE
Trading Post selection in form

### ISSUE THREAD

**Issue by derekfreed** [RedGlow/TheLegendaryQuest#29]
This selection menu is a little unintuitive at first as to what it does. Make it more clear that this is for determining the total costs. A new user might think they have somehow given you access to buy the remaining items for them.

**Comment by RedGlow** [comment]
Hi!
Sorry, I'm a bit unclear to what you are exactly referring to with "this selection menu". Is the "Trading Post" one?

**Comment by derekfreed** [comment]
yeah, the selection menu for the trading post where you select either buy now or place order.

**Comment by RedGlow** [comment]
I get what you mean.
I would probably keep the same text as in the real trading post ("buy instantly" and "place order") and change the label. Perhaps to "Trading Post Costs"? Do you have any suggestion?

**Comment by derekfreed** [comment]
I think "Estimated Costs" or "Trading Post Costs" works well

**Comment by RedGlow** [comment]
Very good, fixed by https://github.com/RedGlow/TheLegendaryQuest/commit/6f9d3ff04c963edcbbf4d0e4beee1e363053ac87. Thanks for the input!
